### ISSUE TITLE
Captive user space are not starting

### ISSUE THREAD

**Issue by sielf** [avisi-group/captive#6]
I've built captive as presented in Readme, tried to use own kernel, and prebuilt one.
Own aarch64 fails with unknown instruction, so I started with presented in Readme kernel.
There are no rootfs binded to repo, so I used way to build as in first issue:
dd if=/dev/zero of=./archlinux.ext2 bs=4M count=1000
```
mkfs.ext4 ./archlinux.ext2
sudo mount ./archlinux.ext2 check
wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
bsdtar -xpf ArchLinuxARM-aarch64-latest.tar.gz -C ./check
sudo chmod a+w check
```
and run as
```
./bin/captive --block-dev-file ./archlinux.ext2 \
--engine arch/arm64.arch \
--device-tree ./captive-platform.dtb \
--kernel ./arm64-kernel-image \
--platform virt
```
So the kernel ran well. There is no init file, so I made link to ./sbin/init but I receive next error:
```
[    2.400000] Run /init as init process
*** unknown instruction: 6e22a446
```
Looks like, I cant run aarch64 executable. What I am doing wrong?

**Comment by tspink** [comment]
Hi,

Thanks for trying this out!

Unfortunately, the Aarch64 model implemented by Captive is relative old, and newer compilers are generating instructions that are not implemented by the model.  This is because developing the full AArch64 model is incredibly time consuming, and so only instructions that we observed were prioritised.

You may have better luck using an older compiler version, to generate binaries that do not contain newer instructions - as the problem is simply that those instructions you're seeing haven't been implemented.

Best wishes,
Tom

**Comment by sielf** [comment]
Hi!
Yesterday I have found the rootfs image which you proposed and it was started! Thanks a lot!
Do you have any suggestions about how deep level of optimization you use? I have found that you use 03, but not sure if it is really O3. 
Also coremark have shown 4 times less performance in comparison to qemu 7.1. May that was due to compilator optimization level?

**Comment by tspink** [comment]
Thanks for trying it out - I'm glad you got it started.

There are a number of different components that could be optimised - which specific one are you asking about?  There's the bare metal kernel that does the DBT runtime, there's the KVM hypervisor, and there are the user applications etc running inside Captive.  As far as I remember, I'm pretty sure everything is on O3.

As for performance - I'm not surprised that things have slipped.  Again, Captive was developed a while ago (back in 2017/18), and so was compared against much older versions of Qemu.  Qemu has simply just gotten better, and Captive is no longer actively developed (we're working on a newer, shinier version), so it hasn't kept up with advancements in the Qemu runtime.

Best wishes,
Tom

**Comment by sielf** [comment]
Thanks a lot! That is a really good good job!
The last question, does it supports multicore right now?

**Comment by tspink** [comment]
You're welcome!

It does not support multicore in the guest architecture - that is a severe limitation of Captive, which we hope to overcome in the future.

Best wishes,
Tom

**Comment by sielf** [comment]
Started
